const mockSurveyData = [
  {
    "objectid": 1,
    "date_mission": "2026-05-12",
    "region_admin": "Cacheu",
    "secteur_admin": "Cacheu",
    "village": "Elia",
    "nom_site": "Elia Nord",
    "crit_1": "oui",
    "crit_1_justif": "Anciennes rizières abandonnées envahies par des herbes d'eau salée.",
    "crit_2": "oui",
    "crit_2_justif": "Situé dans la zone tampon du Parc Naturel des Mangroves de Cacheu.",
    "crit_3": "oui",
    "crit_3_justif": "Aucun autre projet actif identifié sur cette zone.",
    "crit_4": "oui",
    "crit_4_justif": "Classé non-forêt sur la carte REDD+ de 2011.",
    "crit_5": "oui",
    "crit_5_justif": "Rizières abandonnées depuis 2018 en raison de l'intrusion saline.",
    "crit_6": "oui",
    "crit_6_justif": "Digue en terre rompue empêchant le drainage régulier de la marée.",
    "crit_7": "oui",
    "crit_7_justif": "Mangroves existantes totalement dégradées ou mortes.",
    "crit_8": "oui",
    "crit_8_justif": "Aucune régénération naturelle observée sur le site.",
    "crit_9": "oui",
    "crit_9_justif": "Consentement écrit signé par le chef de village et le comité local.",
    "crit_10": "oui",
    "crit_10_justif": "Propriété communautaire claire sans aucun litige en cours.",
    "site_eligible": "oui",
    "diff_technique": 2,
    "diff_technique_justif": "Nécessite la réparation partielle de la digue et l'ouverture de deux petits chenaux.",
    "diff_communaute": 1,
    "diff_communaute_justif": "Forte adhésion de l'association locale des femmes pour le reboisement.",
    "diff_accessibilite": 2,
    "diff_accessibilite_justif": "Accessible en pirogue à moteur depuis Cacheu (45 min de trajet).",
    "diff_taille": 1,
    "diff_taille_justif": "Superficie de 12 hectares, taille optimale pour le budget disponible.",
    "diff_physicochimique": 2,
    "diff_physicochimique_justif": "Salinité modérée, présence de propagules à proximité.",
    "score_final": 8,
    "site_selectionne": "oui",
    "decision_commentaire": "Site hautement prioritaire avec un fort engagement communautaire et des conditions écologiques favorables pour une restauration active.",
    "latitude": 12.2854,
    "longitude": -16.3210
  },
  {
    "objectid": 2,
    "date_mission": "2026-05-14",
    "region_admin": "Cacheu",
    "secteur_admin": "São Domingos",
    "village": "Jobel",
    "nom_site": "Jobel Estuaire",
    "crit_1": "oui",
    "crit_1_justif": "Anciennes tannes surélevées par le dépôt sédimentaire.",
    "crit_2": "oui",
    "crit_2_justif": "Dans les limites du Parc Naturel de Cacheu.",
    "crit_3": "oui",
    "crit_3_justif": "Aucune autre initiative sur le site.",
    "crit_4": "oui",
    "crit_4_justif": "Zone herbeuse non arborée sur la carte REDD+.",
    "crit_5": "oui",
    "crit_5_justif": "Abandonné depuis 2015 après la salinisation des puits.",
    "crit_6": "oui",
    "crit_6_justif": "Canal d'alimentation obstrué par des sédiments.",
    "crit_7": "oui",
    "crit_7_justif": "Présence de quelques troncs morts de mangroves.",
    "crit_8": "oui",
    "crit_8_justif": "Pas de régénération naturelle en raison de l'obstruction hydrologique.",
    "crit_9": "oui",
    "crit_9_justif": "Accord signé lors de la réunion de consultation publique.",
    "crit_10": "oui",
    "crit_10_justif": "Zone gérée par les aînés du village, pas de conflit.",
    "site_eligible": "oui",
    "diff_technique": 1,
    "diff_technique_justif": "Restauration hydrologique simple par curetage manuel du canal principal.",
    "diff_communaute": 1,
    "diff_communaute_justif": "La communauté réclame ce projet pour restaurer les stocks de poissons.",
    "diff_accessibilite": 2,
    "diff_accessibilite_justif": "Piste praticable uniquement en saison sèche, sinon par voie fluviale.",
    "diff_taille": 1,
    "diff_taille_justif": "8 hectares, facile à gérer et à suivre par le village.",
    "diff_physicochimique": 1,
    "diff_physicochimique_justif": "Excellente vase de mangrove, pH neutre et bonne inondation tidale.",
    "score_final": 6,
    "site_selectionne": "oui",
    "decision_commentaire": "C'est le site idéal : technique simple, communauté dynamique, conditions écologiques parfaites.",
    "latitude": 12.3950,
    "longitude": -16.2140
  },
  {
    "objectid": 3,
    "date_mission": "2026-05-15",
    "region_admin": "Cacheu",
    "secteur_admin": "Cacheu",
    "village": "Apilhao",
    "nom_site": "Apilhao Ouest",
    "crit_1": "oui",
    "crit_1_justif": "Ancien lit de rivière asséché.",
    "crit_2": "oui",
    "crit_2_justif": "Dans le Parc Naturel de Cacheu.",
    "crit_3": "oui",
    "crit_3_justif": "Pas d'autre projet.",
    "crit_4": "non",
    "crit_4_justif": "Le site est classé comme forêt dense de mangrove sur la carte REDD+ de 2011, ce qui constitue une exclusion automatique.",
    "crit_5": "oui",
    "crit_5_justif": "Pas d'activité agricole active.",
    "crit_6": "oui",
    "crit_6_justif": "Hydrologie altérée par une route construite à proximité.",
    "crit_7": "non",
    "crit_7_justif": "Présence de franges de mangroves saines qui se régénèrent.",
    "crit_8": "non",
    "crit_8_justif": "Régénération naturelle importante déjà active sur 60% de la surface.",
    "crit_9": "oui",
    "crit_9_justif": "Consentement obtenu.",
    "crit_10": "oui",
    "crit_10_justif": "Pas de conflit.",
    "site_eligible": "non",
    "diff_technique": 2,
    "diff_technique_justif": "Ouverture d'une buse sous la route requise.",
    "diff_communaute": 2,
    "diff_communaute_justif": "Intérêt modéré des jeunes du village.",
    "diff_accessibilite": 1,
    "diff_accessibilite_justif": "Bord de route nationale, accès très facile.",
    "diff_taille": 2,
    "diff_taille_justif": "18 hectares.",
    "diff_physicochimique": 2,
    "diff_physicochimique_justif": "Bonne vase mais sédimentation rapide.",
    "score_final": 9,
    "site_selectionne": "non",
    "decision_commentaire": "REJETÉ. Le site n'est pas éligible car il présente déjà une régénération naturelle dynamique et est classé forêt sur la carte de référence REDD+.",
    "latitude": 12.2610,
    "longitude": -16.2520
  },
  {
    "objectid": 4,
    "date_mission": "2026-05-20",
    "region_admin": "Tombali",
    "secteur_admin": "Bedanda",
    "village": "Guilege",
    "nom_site": "Guilege Rizières",
    "crit_1": "oui",
    "crit_1_justif": "Rizières traditionnelles (bolanhas) abandonnées.",
    "crit_2": "oui",
    "crit_2_justif": "Situé dans la zone périphérique du Parc National de Cantanhez.",
    "crit_3": "oui",
    "crit_3_justif": "Aucun projet concurrent.",
    "crit_4": "oui",
    "crit_4_justif": "Classé non-forêt sur la référence REDD+.",
    "crit_5": "oui",
    "crit_5_justif": "Abandonné depuis 2012 après rupture définitive des digues de protection.",
    "crit_6": "oui",
    "crit_6_justif": "Accumulation excessive de sel due à un manque de lessivage.",
    "crit_7": "oui",
    "crit_7_justif": "Végétation de mangrove inexistante.",
    "crit_8": "oui",
    "crit_8_justif": "Pas de régénération naturelle.",
    "crit_9": "oui",
    "crit_9_justif": "Consentement écrit signé par les propriétaires terriens et le chef de village.",
    "crit_10": "oui",
    "crit_10_justif": "Pas de dispute foncière enregistrée.",
    "site_eligible": "oui",
    "diff_technique": 3,
    "diff_technique_justif": "Difficulté technique élevée : Salinité extrême du sol. Nécessite un lessivage hivernal préalable et des travaux de terrassement importants.",
    "diff_communaute": 2,
    "diff_communaute_justif": "Main d'œuvre disponible mais nécessite des formations et une sensibilisation accrue.",
    "diff_accessibilite": 3,
    "diff_accessibilite_justif": "Très difficile d'accès en saison des pluies (piste de boue de 20 km en 4x4).",
    "diff_taille": 2,
    "diff_taille_justif": "15 hectares.",
    "diff_physicochimique": 2,
    "diff_physicochimique_justif": "Acidité élevée du sol, nécessite un suivi rigoureux du pH.",
    "score_final": 12,
    "site_selectionne": "oui",
    "decision_commentaire": "Sélectionné malgré une difficulté globale élevée (12/15) en raison de sa position stratégique pour reconnecter des corridors hydrologiques majeurs dans le Parc de Cantanhez.",
    "latitude": 11.1980,
    "longitude": -15.1520
  },
  {
    "objectid": 5,
    "date_mission": "2026-05-22",
    "region_admin": "Tombali",
    "secteur_admin": "Cacine",
    "village": "Iemberem",
    "nom_site": "Iemberem Fluvial",
    "crit_1": "oui",
    "crit_1_justif": "Zone déboisée en bordure de fleuve.",
    "crit_2": "oui",
    "crit_2_justif": "Au cœur du Parc National de Cantanhez.",
    "crit_3": "oui",
    "crit_3_justif": "Aucune initiative concurrente.",
    "crit_4": "oui",
    "crit_4_justif": "Non répertorié comme forêt dense en 2011.",
    "crit_5": "oui",
    "crit_5_justif": "Ancienne zone d'exploitation abandonnée il y a 4 ans.",
    "crit_6": "oui",
    "crit_6_justif": "Dépôt d'alluvions bloquant la marée haute.",
    "crit_7": "oui",
    "crit_7_justif": "Frange arbustive morte.",
    "crit_8": "oui",
    "crit_8_justif": "Pas de régénération naturelle spontanée.",
    "crit_9": "oui",
    "crit_9_justif": "Adhésion totale signée avec la charte communautaire locale.",
    "crit_10": "oui",
    "crit_10_justif": "Limites de propriété validées par le conseil du village.",
    "site_eligible": "oui",
    "diff_technique": 1,
    "diff_technique_justif": "Creusement simple de chenaux d'écoulement pour rétablir la marée.",
    "diff_communaute": 1,
    "diff_communaute_justif": "Comité de gestion du parc national très actif et prêt à réaliser les travaux.",
    "diff_accessibilite": 2,
    "diff_accessibilite_justif": "Accessible par bateau depuis Cacine (30 min).",
    "diff_taille": 2,
    "diff_taille_justif": "25 hectares, grand potentiel de séquestration carbone.",
    "diff_physicochimique": 1,
    "diff_physicochimique_justif": "Sol humide excellent, pH optimal autour de 6.5.",
    "score_final": 7,
    "site_selectionne": "oui",
    "decision_commentaire": "Excellent site pour la restauration communautaire active. Grand potentiel de séquestration et de sensibilisation pour le Parc de Cantanhez.",
    "latitude": 11.2340,
    "longitude": -15.0290
  },
  {
    "objectid": 6,
    "date_mission": "2026-05-23",
    "region_admin": "Tombali",
    "secteur_admin": "Bedanda",
    "village": "Lautchande",
    "nom_site": "Lautchande Marais",
    "crit_1": "oui",
    "crit_1_justif": "Zone inondable dégradée.",
    "crit_2": "oui",
    "crit_2_justif": "Zone périphérique de Cantanhez.",
    "crit_3": "oui",
    "crit_3_justif": "Pas d'autre projet.",
    "crit_4": "oui",
    "crit_4_justif": "Classé non-forêt.",
    "crit_5": "oui",
    "crit_5_justif": "Abandonné depuis 3 ans.",
    "crit_6": "oui",
    "crit_6_justif": "Inondation permanente d'eau stagnante due à une digue fermée.",
    "crit_7": "oui",
    "crit_7_justif": "Pas de mangrove saine.",
    "crit_8": "oui",
    "crit_8_justif": "Pas de régénération naturelle.",
    "crit_9": "oui",
    "crit_9_justif": "Accord verbal mais réticences de certains éleveurs.",
    "crit_10": "non",
    "crit_10_justif": "Litige foncier majeur persistant entre deux familles concernant les droits d'usage de la bolanha abandonnée.",
    "site_eligible": "non",
    "diff_technique": 2,
    "diff_technique_justif": "Nécessite de percer la digue.",
    "diff_communaute": 3,
    "diff_communaute_justif": "Tensions communautaires fortes risquant de compromettre la pérennité du projet.",
    "diff_accessibilite": 2,
    "diff_accessibilite_justif": "Accès moyen en piste forestière.",
    "diff_taille": 1,
    "diff_taille_justif": "5 hectares.",
    "diff_physicochimique": 2,
    "diff_physicochimique_justif": "Eau stagnante acide.",
    "score_final": 10,
    "site_selectionne": "non",
    "decision_commentaire": "REJETÉ. Non-éligibilité en raison du conflit foncier (critère 10) et de la faible cohésion sociale sur le projet.",
    "latitude": 11.1640,
    "longitude": -15.1180
  },
  {
    "objectid": 7,
    "date_mission": "2026-05-25",
    "region_admin": "Cacheu",
    "secteur_admin": "São Domingos",
    "village": "Caboxanque",
    "nom_site": "Caboxanque Sud",
    "crit_1": "oui",
    "crit_1_justif": "Anciens marais salants artisanaux abandonnés.",
    "crit_2": "oui",
    "crit_2_justif": "Proche de la frontière nord, dans le Parc de Cacheu.",
    "crit_3": "oui",
    "crit_3_justif": "Pas d'autre projet.",
    "crit_4": "oui",
    "crit_4_justif": "Classé non-forêt.",
    "crit_5": "oui",
    "crit_5_justif": "Salines abandonnées depuis 2020.",
    "crit_6": "oui",
    "crit_6_justif": "Dunes de sable artificielles bloquant la marée descendante.",
    "crit_7": "oui",
    "crit_7_justif": "Absence totale de mangrove.",
    "crit_8": "oui",
    "crit_8_justif": "Pas de régénération possible à cause du niveau élevé de sel cristallisé.",
    "crit_9": "oui",
    "crit_9_justif": "Consentement des villageois obtenu par procès-verbal.",
    "crit_10": "oui",
    "crit_10_justif": "Propriété d'État louée à la communauté, pas de litige.",
    "site_eligible": "oui",
    "diff_technique": 3,
    "diff_technique_justif": "Nécessite d'araser les dunes de sel et de laver le sol sur plusieurs saisons des pluies.",
    "diff_communaute": 3,
    "diff_communaute_justif": "Le village est très éloigné, main d'œuvre très limitée sur place pour les corvées physiques.",
    "diff_accessibilite": 2,
    "diff_accessibilite_justif": "Piste sableuse difficile mais praticable en quad ou tracteur.",
    "diff_taille": 3,
    "diff_taille_justif": "3 hectares (très petit site, rentabilité faible par rapport aux investissements requis).",
    "diff_physicochimique": 3,
    "diff_physicochimique_justif": "Concentration de sel extrême, sol dur comme du béton par endroits.",
    "score_final": 14,
    "site_selectionne": "non",
    "decision_commentaire": "NON SÉLECTIONNÉ. Bien qu'éligible théoriquement, la difficulté globale est de 14/15. Le rapport coût/bénéfice pour 3 hectares est trop défavorable.",
    "latitude": 12.4410,
    "longitude": -16.2790
  },
  {
    "objectid": 8,
    "date_mission": "2026-05-28",
    "region_admin": "Tombali",
    "secteur_admin": "Cacine",
    "village": "Cabedu",
    "nom_site": "Cabedu Port",
    "crit_1": "oui",
    "crit_1_justif": "Zone de lagunes dégradées près du quai.",
    "crit_2": "oui",
    "crit_2_justif": "Zone tampon du Parc National de Cantanhez.",
    "crit_3": "oui",
    "crit_3_justif": "Pas d'autre projet.",
    "crit_4": "oui",
    "crit_4_justif": "Classé non-forêt.",
    "crit_5": "oui",
    "crit_5_justif": "Abandonné depuis 2019.",
    "crit_6": "oui",
    "crit_6_justif": "Pollution aux hydrocarbures légère et sédimentation lourde gênant la marée.",
    "crit_7": "oui",
    "crit_7_justif": "Mangroves existantes quasi nulles.",
    "crit_8": "oui",
    "crit_8_justif": "Régénération bloquée par le passage régulier des pirogues.",
    "crit_9": "oui",
    "crit_9_justif": "Consentement validé par le syndicat des pêcheurs locaux.",
    "crit_10": "oui",
    "crit_10_justif": "Usage public reconnu.",
    "site_eligible": "oui",
    "diff_technique": 2,
    "diff_technique_justif": "Retrait des déchets physiques et déviation du canal des pirogues requis.",
    "diff_communaute": 2,
    "diff_communaute_justif": "Forte volonté des pêcheurs mais requiert un contrôle permanent pour éviter les nouveaux déchets.",
    "diff_accessibilite": 1,
    "diff_accessibilite_justif": "Directement accessible depuis le quai de Cabedu.",
    "diff_taille": 2,
    "diff_taille_justif": "10 hectares.",
    "diff_physicochimique": 2,
    "diff_physicochimique_justif": "Sol argileux fertile, présence de propagules (mangroves avoisinantes).",
    "score_final": 9,
    "site_selectionne": "oui",
    "decision_commentaire": "Sélectionné. Permet de sensibiliser le public au niveau du port local et de stopper l'érosion côtière menaçant les infrastructures portuaires.",
    "latitude": 11.1350,
    "longitude": -15.0210
  }
];

// Export to window if running in browser
if (typeof window !== 'undefined') {
  window.mockSurveyData = mockSurveyData;
}
